# Generated by Django 3.0.5 on 2020-04-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='text',
        ),
    ]
