# Generated by Django 3.0.5 on 2020-05-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200411_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_date',
            new_name='note_created_date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='note_name',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='note_text',
        ),
    ]
